services:
  boletas-app:
    build: .
    container_name: boletas_django_app
    restart: always
    env_file:
      - .env
    ports:
      - "8003:8000"
    volumes:
      - boletas_media:/app/media
      - boletas_static:/app/static_root
    networks:
      - siit_net
      - proxy_network

networks:
  siit_net:
    external: true
    name: siit-api_siit_net
  proxy_network:
    external: true
    name: proxy_network

volumes:
  boletas_media:
  boletas_static: