# Generated by Django 5.2.7 on 2025-11-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_description_alter_profile_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descriptionSP',
            field=models.TextField(blank=True, null=True),
        ),
    ]
