# Generated by Django 5.2.7 on 2025-11-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_descriptionsp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='payment_date',
            new_name='resigned_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
