# Generated by Django 5.2.7 on 2025-11-04 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_payment_date_profile_resigned_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileWorkDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('worked_days', models.PositiveIntegerField(default=0)),
                ('non_worked_days', models.PositiveIntegerField(default=0)),
                ('worked_hours', models.PositiveIntegerField(default=0)),
                ('discount_academic_hours', models.PositiveIntegerField(default=0)),
                ('discount_lateness', models.PositiveIntegerField(default=0)),
                ('personal_leave_hours', models.PositiveIntegerField(default=0)),
                ('sunday_discount', models.PositiveIntegerField(default=0)),
                ('vacation_days', models.PositiveIntegerField(default=0)),
                ('vacation_hours', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
