# Generated by Django 5.2.7 on 2025-11-03 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('issue_date', models.DateField()),
                ('pdf_file', models.CharField(max_length=255)),
                ('view_status', models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen'), ('downloaded', 'Downloaded')], default='unseen', max_length=20)),
                ('concept', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_source', models.CharField(max_length=100)),
                ('payroll_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('position_order', models.PositiveIntegerField()),
                ('worked_days', models.PositiveIntegerField(default=0)),
                ('non_worked_days', models.PositiveIntegerField(default=0)),
                ('worked_hours', models.PositiveIntegerField(default=0)),
                ('discount_academic_hours', models.PositiveIntegerField(default=0)),
                ('discount_lateness', models.PositiveIntegerField(default=0)),
                ('personal_leave_hours', models.PositiveIntegerField(default=0)),
                ('sunday_discount', models.PositiveIntegerField(default=0)),
                ('vacation_days', models.PositiveIntegerField(default=0)),
                ('vacation_hours', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
