# Generated by Django 5.2.7 on 2025-11-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='discount_academic_hours',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='discount_lateness',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='non_worked_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='personal_leave_hours',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='sunday_discount',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='vacation_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='vacation_hours',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='worked_days',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='worked_hours',
        ),
    ]
