# Generated by Django 5.2.7 on 2025-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0002_remove_payslip_discount_academic_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
