# Generated by Django 5.2.7 on 2025-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0003_alter_payslip_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='view_status',
            field=models.CharField(choices=[('unseen', 'No visto'), ('seen', 'Visto'), ('generated', 'Generado')], default='unseen', max_length=20),
        ),
    ]
