name: Deploy Backend to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH to AWS Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/proyectos
            cd ~/proyectos

            if [ ! -d "digital-payroll-system-backend" ]; then
              git clone https://github.com/Luis3Fernando/digital-payroll-system-backend.git digital-payroll-system-backend
              cd digital-payroll-system-backend
            else
              cd digital-payroll-system-backend
              git fetch origin main
              git reset --hard origin/main
            fi

            sudo docker compose up -d --build --remove-orphans
            echo "¡Despliegue de Boletas completado con éxito!"